general:
  use_sandbox: true
  
mqtt:
  host: 10.0.0.243
  port: 1883
  
redis:
  host: 127.0.0.1
  port: 6379
  auth: doordu
    
a47a7898481eabf77a1a5ce061f7908b:
  apns:
    cert_filename: doordu
    passphrase: doordu123456
    bundle_id: com.doordu.doordushijie
  huawei:
    client_id: 10201628
    client_secret: sv76t42d7qcashyjjz1s5hxzrubuuvvf
  xiaomi:
    package_name: com.doordu.mobile
    secret_key: xJB7WtOurXuwwP4zKGdDLQ==
  meizu:
    app_id: 110015
    secret_key: 1e3412be25f44814827811fed0a1ff2c
    
    
707c1b60fc22378fc22d4bd51bce7616:
  apns:
    cert_filename: lingju
    passphrase: lingju654321
    bundle_id: com.lingjulive.mobile
  huawei:
    client_id: 10748808
    client_secret: 0819d7a11f16f739d63152394f4d2641
  xiaomi:
    package_name: com.lingjulive.mobile
    secret_key: IjY3Y6xDubozNxDdiRbRiA==
  meizu:
    app_id: 110170
    secret_key: d3a4a041afd949408c8d23668fe167b8


195715545587f05038f77a42317efb84:
  apns:
    cert_filename: yijiaqin
    passphrase: Doordu123456
    bundle_id: com.yijiaqin.mobile
  huawei:
    client_id: 10803759
    client_secret: f1e48560099e705c251c1e4947cdad79
  xiaomi:
    package_name: com.yijiaqin.mobile
    secret_key: t7C5YkBwOiRbotO2RaP4hQ==
  meizu:
    app_id: 110231
    secret_key: d5085a0c28be4ce59678847d90c55e59

banshenghuo:
  apns:
    cert_filename: banshenghuo
    passphrase: banshenghuo123
    bundle_id: com.banshenghuo.banshenghuo
  huawei:
    client_id: 10746637
    client_secret: 9788943d64c57292f196e797d19f253b
  xiaomi:
    package_name: com.banshenghuo.mobile
    secret_key: U/GAxT5BOOMdCwkGFQYrKA==
  meizu:
    app_id: 110272
    secret_key: 132c402b651741e48b5385722fd18aa0
