#!/bin/bash
#
# gunicorn for doordu push
#
# chkconfig:   - 20 80
. /etc/rc.d/init.d/functions

PROG_NAME="gunicorn"
PRO_PATH="/usr/local/doordu-push-new"
PRO_BIN="gunicorn"
PRO_PID_FILE="${PRO_PATH}/${PROG_NAME}.pid"
HOST="127.0.0.1"
PORT="1884"
FORK="4"

cd $PRO_PATH
source env/bin/activate
RETVAL=0

start(){
    echo -n $"Starting $PROG_NAME: "
    $PRO_BIN main:app -w $FORK -b $HOST:$PORT & echo $! > $PRO_PID_FILE &
    RETVAL=$?
}
stop()
{
    echo -n $"Stopping $PROG_NAME: "
    head -1 $PRO_PID_FILE | xargs kill -9
    sleep 5
    [ $RETVAL = 0 ] && rm -f $PRO_PID_FILE
    RETVAL=$?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
     restart)
        stop && start
        ;;
    help)
        $0 -h
        ;;
     *)
         echo $"Usage: $PROG_NAME {start | stop | restart | help}"

esac
exit $RETVAL
